In [3]:
import torch
import numpy as np

In [4]:
# 创建张量
t1=torch.zeros(3,2)
t2=torch.tensor([[3,2,3],[1,2,3],[3,2,1]])
t2

tensor([[3, 2, 3],
        [1, 2, 3],
        [3, 2, 1]])

In [5]:
# tensor中的数据时连续分配在内存中，由torch.Storage实例管理
t2_storage = t2.storage() # t2的存储实例是一维的连续数组,类似将对应的数组resheap为(-1,1)
t2_storage.size

<bound method _TypedStorage.size of  3
 2
 3
 1
 2
 3
 3
 2
 1
[torch.LongStorage of size 9]>

In [6]:
t2_storage[1]

2

In [7]:
t2_storage[4] = 2 #通过更改存储的值来更改引用它的张量的内容

In [8]:
t2

tensor([[3, 2, 3],
        [1, 2, 3],
        [3, 2, 1]])

In [9]:
'''
通过dtype查看数据类型，与numpy一样
torch.float32或torch.float —— 32位浮点数
torch.float64或torch.double —— 64位双精度浮点数
torch.float16或torch.half —— 16位半精度浮点数
torch.int8 —— 带符号8位整数
torch.uint8 —— 无符号8位整数
torch.int16或torch.short —— 带符号16位整数
torch.int32或torch.int —— 带符号32位整数
torch.int64或torch.long —— 带符号64位整数
'''
t2.dtype

torch.int64

In [10]:
# 使用.方法和to()进行类型转换
double = torch.zeros(10, 2).to(torch.double)
short  = torch.ones(10, 2).to(dtype=torch.short)

In [11]:
# 与numpy互通

# 从points张量创建NumPy数组
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [12]:
# NumPy数组创建Tensor张量
points_numpy = np.ones((3,4))
points_tensor = torch.from_numpy(points_numpy)
points_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [13]:
#将其保存到文件中并在某个时候加载回去。杜绝每次开始运行程序时从头开始重新训练模型————将points张量保存到ourpoints.t文件中
torch.save(points, './ourpoints.t')   # .t文件只能通过pytorch打开

# 另：可将points张量转换为NumPy数组，并将其传递给create_dataset函数来保存points张量
import h5py

f = h5py.File('./ourpoints.hdf5', 'w')   # 用于创建新的文件对象
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [14]:
# 张量在GPU上运行
# 添加device参数
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')   #如此，将数据存放在本地GPU中
points_gpu

tensor([[1., 4.],
        [2., 1.],
        [3., 4.]], device='cuda:0')

In [15]:
# 也可使用to方法
points_gpu = points.to(device='cuda')

In [16]:
#对于多核GPU，传递从零开始的整数来确定张量分配给哪个GPU
points_gpu_to = points.to(device='cuda:0')

神经网络将浮点表示形式转换为其他浮点表示形式，起始和结束的表示形式通常是可以理解的，但中间表示则不是这样。
这些浮点表示存储在张量中。
张量是多维数组，它是PyTorch中的基本数据结构。
PyTorch有一个全面的标准库，用于张量创建、操作和数学运算。
张量可以序列化存储到磁盘上也可以加载回来。
PyTorch中的所有张量操作都可以在CPU和GPU上执行，无需更改代码。
PyTorch使用结尾下划线标识来表示就地操作（例如Tensor.sqrt_）张量API

少量操作仅作为张量对象的方法存在。
可通过名称中的下划线来识别，例：zero_，下划线标识表明该方法是就地（inplace）运行的，即直接修改输入而不是创建新的输出并返回。
zero_方法会将输入的所有元素清零。任何不带下划线的方法都将保持源张量不变并返回新的张量：

In [17]:
a = torch.ones(3, 2)
a.zero_()   # 不保留原有值，就地执行
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### Tensor 运算

In [18]:
t=torch.tensor([[3,-2,3],[-1,2,3],[-3,2,1]])
t_=torch.tensor([[1,-3,2],[3,2,1],[2,1,2]])

# torch.abs(arg1)
# 输入参数：Tensor数据类型的变量
# 输出：输入参数的绝对值

# torch.add(arg1,arg2)
# 输入参数：既可以全部是tensor数据类型的变量，也可以一个是tensor数据类型的变量，另一个是标量
# 输出：返回输入参数的求和结果
# 与numpy中的矩阵加法运算一样

# torch.clamp()
# 对输入参数按照自定义的范围进行裁剪，最后将参数裁剪的结果作为输出
# 输入参数：torch.clamp(arg,a,b)
# 具体裁剪过程：对于张量arg中的元素，小于a的赋值为a,大于b的赋值为b,介于(a，b）的元素保留
# 输出：将裁剪结果输出

# torch.div(arg,a) /  torch.div(arg1,arg2)
# 对张量除标量，或两个张量对应元素相除
# 输出：返回输入参数的求商结果

# torch.mul()
# 求数量积，参数同torch.div()

# torch.pow()
# 求幂，参数设置同上

# torch.mm()
# 求积
# torch.mm()采用矩阵乘法，被传入的参数被当做矩阵进行处理，参数形状需满足矩阵乘法的条件

# torch.mv()
# 求积结
# torch.mv()运用矩阵与向量之间的乘法规则运算，被传入的参数中第1个参数代表矩阵，第2个采纳数代表向量，顺序不能颠倒。

### 自动求导
#### 神经网络内部和优化期间的所有操作都是张量之间的操作，而神经网络中的所有参数（例如权重和偏差）也都是张量。掌握如何在张量上执行操作并对其进行有效索引是成功使用PyTorch等工具的关键

In [19]:
# 使用torch.autograd完成神经网络反向传播中的链式求导
# tensor可以记住它们来自什么运算以及其起源的父张量，并且提供相对于输入的导数链。无需手动对模型求导：不管如何嵌套，只要给出前向传播表达式，PyTorch都会自动提供该表达式相对于其输入参数的梯度
# 实现auto compute grad 的大致过程：
# 1.通过输入的tensor数据类型的变量在神经网络中的前向传播过程生成一张计算图
# 2.根据这个计算图和输出结果准确计算出每个参数需要更新的梯度，并通过完成反向传播完成对参数的梯度更新

In [20]:
# 所有PyTorch张量都有一个初始为空的名为grad的属性：
torch.autograd.grad is None # True

False